name: football_tracker
description: "FutTracker - Football Performance Tracker"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.3.3+1
  path: ^1.9.0
  google_fonts: ^6.2.1
  intl: ^0.19.0
  provider: ^6.1.2
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "icon_source.png"
  image_path_android: "icon_source.png"
  image_path_ios: "icon_source.png"
  remove_alpha_ios: true
